# Generated by Django 6.0.7 on 2026-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
