apiVersion: v1
kind: Service
metadata:
  name: book-catalog-internal
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    service: book-catalog # Make sure this matches the `.spec.template.metadata.labels` from the deployment
  type: ClusterIP
